- id: chktex
  name: chktex (via docker image)
  description: "Checks LaTeX files with ChkTeX."
  entry: --entrypoint chktex joclement/chktex:latest
  language: docker_image
  types: [tex]
- id: lacheck
  name: lacheck (via docker image)
  description: "Checks LaTeX files with lacheck."
  entry: --entrypoint lacheck joclement/lacheck:latest
  language: docker_image
  types: [tex]
