---
ci:
  autoupdate_schedule: quarterly
  skip: [hadolint-docker]

repos:
- repo: meta
  hooks:
  - id: check-hooks-apply
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: c4a0b883114b00d8d76b479c820ce7950211c99b  # frozen: v4.5.0
  hooks:
  - id: check-case-conflict
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/commitizen-tools/commitizen
  rev: 669080c8c180a1f81bc3f0666b0d49fb71ab6dde  # frozen: v3.21.3
  hooks:
  - id: commitizen
  - id: commitizen-branch
    stages: [push]
- repo: https://github.com/hadolint/hadolint
  rev: 02c491342ac7c7a4c0617c01ddd51f49010a77f6  # frozen: v2.12.1-beta
  hooks:
  - id: hadolint-docker
