- id: chktex-system
  name: chktex (via system executable)
  description: "Checks LaTeX files with ChkTeX."
  entry: chktex
  language: system
  types: [tex]
- id: chktex-docker
  name: chktex (via docker image)
  description: "Checks LaTeX files with ChkTeX."
  entry: --entrypoint chktex cnservices/chktex@sha256:b6b71442850d9bf62ebd3ce393431b20cc008a12d896f0f84bfa9ee7c4a8725b
  language: docker_image
  types: [tex]
