---
ci:
  autoupdate_schedule: quarterly
  skip: [hadolint-docker]

repos:
- repo: meta
  hooks:
  - id: check-hooks-apply
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c  # frozen: v4.6.0
  hooks:
  - id: check-case-conflict
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/commitizen-tools/commitizen
  rev: e9aa5d979ea6fd14dcf59c6bd3836bef17d386c1  # frozen: v3.27.0
  hooks:
  - id: commitizen
  - id: commitizen-branch
    stages: [push]
- repo: https://github.com/hadolint/hadolint
  rev: 80e0d3d0c58dcdcbced97854ab7c5cf00a5f1a86  # frozen: v2.13.0-beta
  hooks:
  - id: hadolint-docker
