---
ci:
  autoupdate_schedule: quarterly
  skip: [hadolint-docker]

repos:
- repo: meta
  hooks:
  - id: check-hooks-apply
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
  hooks:
  - id: check-case-conflict
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/commitizen-tools/commitizen
  rev: 27499d727f5ceff802bda34bbda314644824ce06  # frozen: v4.1.0
  hooks:
  - id: commitizen
  - id: commitizen-branch
    stages: [pre-push]
- repo: https://github.com/hadolint/hadolint
  rev: c3dc18df7a501f02a560a2cc7ba3c69a85ca01d3  # frozen: v2.13.1-beta
  hooks:
  - id: hadolint-docker
